theme: jekyll-theme-leap-day

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Basically Basic
email: dugan.nash@mailinator.com
description: "Your new default Jekyll theme"
baseurl: "/example"  # the subpath of your site, e.g. /blog
url: "https://brockzera.github.io/Image-Recognition-OpenCV"  # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Dugan Nash
  twitter: Towlette_Pettetucci
  picture: https://api.adorable.io/avatars/285/johndoe.png
twitter_username: Towlette_Pettetucci
github_username: Towlette_Pettetucci
logo: /assets/icons/basically-basic-logo-light.svg
search: true
search_full_content: true
search_provider: algolia
algolia:
  application_id: QB6HVGBSBA
  index_name: basically-basic
  search_only_api_key: 9d5014e5bbc77372547bce778dfa5663
  powered_by: # true (default), false

# Liquid
liquid:
  error_mode: strict

